on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Log In to Docker
        env:
          DOCKER_USER: "${{ secrets.DOCKER_USER }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Build and Push to Docker
        env:
          REPO: tescevents
        run: |
          docker build -t $REPO TescEvents
          docker tag $REPO:latest ${{ secrets.DOCKER_USER }}/$REPO:latest
          docker push ${{ secrets.DOCKER_USER }}/$REPO
        
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST_DNS }}"
          username: "${{ secrets.USER }}"
          key: "${{ secrets.EC2_SSH_KEY }}"
          envs: GITHUB_SHA
          script: |
            docker login
            docker pull "${{ secrets.DOCKER_USER }}/$REPO"
            docker stop tescevents
            docker rm tescevents
            docker run "${{ secrets.DOCKER_USER }}/$REPO"
